title: Spyglass documentation
description: >-
  Development tools for vanilla Minecraft: Java Edition data pack developers. 
baseurl: ""
url: "https://spyglassmc.com"
github_username:  SpyglassMC

# Build settings
plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from

keep_files:
  - .git
  - playground

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# AsciiDoc
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    source-highlighter: rouge

# Theme
theme: just-the-docs
color_scheme: black
## Footer
gh_edit_link: true
gh_edit_link_text: View the page source on GitHub.
gh_edit_repository: https://github.com/SpyglassMC/Spyglass
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: tree
## Nav
nav_external_links:
  - title: Playground
    url: https://spyglassmc.com/playground/
    hide_icon: true
