name: Commit
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci --legacy-peer-deps

      - run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci --legacy-peer-deps

      - run: npm run prettier

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci --legacy-peer-deps

      - run: npm run build

      - run: npm test

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            packages/*/lib/
            packages/*/out/
            packages/*/dist/
            packages/vscode-extension/**/*.vsix

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - lint
      - prettier
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: packages/
      
      - run: npm run release:dry

      - name: Deploy playground
        if: ${{ github.event_name == 'push' }}
        working-directory: packages/playground
        run: npm run deploy
