name: Publish Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          working-directory: docs

      - uses: limjh16/jekyll-action-ts@v2
        with:
          jekyll_src: docs
          gem_src: docs
          enable_cache: true

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_site
          git-config-name: ${{ secrets.GIT_AUTHOR_NAME }}
          git-config-email: ${{ secrets.GIT_AUTHOR_EMAIL }}
          commit-message: 🚀 Deploy docs
          clean: true
          clean-exclude: |
            playground
          force: false
