name: Test & Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
jobs:
  test-and-deploy:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci --legacy-peer-deps

      - run: npm run build

      - run: npm test

      - run: npm run lint

      - run: npm run release:dry

      - name: Deploy playground
        if: ${{ github.event == "push" }}
        working-directory: packages/playground
        run: npm run deploy
