name: Test & Release
on:
  push:
    branches:
      - released
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
jobs:
  test-and-release:
    name: Test & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - run: |
          npm i
          npm run init

      - run: npm run build

      - run: npm test

      - run: npm run lint

      - run: npm run release
