name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm i -g npm@7

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache tsc build
        uses: actions/cache@v2
        with:
          path: |
            packages/*/lib
            packages/*/out
            packages/*/test-out
          key: ${{ runner.os }}-tsc-build

      - run: npm run clean
        if: "contains(github.event.head_commit.message, '[ci clean]')"

      - run: npm i

      - run: npm run build

      - run: npm test

      - run: npm run lint
