name: Test & Release
on:
  push:
    branches:
      - released
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
jobs:
  test-and-release:
    name: Test & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm i -g npm@7

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: npm run build

      - run: npm test

      - run: npm run release
