name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm i -g npm@7

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - run: |
          npm i
          npm run init

      - run: npm run build

      - run: npm test

      - run: npm run lint
