name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node2-

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: |
          npm test
          npm run codecov

      - name: Lint
        run: npm run lint
